apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: satania
spec:
  schedule: '*/30 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: satania
              image: weeb-poly/satania
              command: ['python']
              args: ['-m', 'app.main']
              volumeMounts:
                - name: satania_secret_vol
                  mountPath: /app/secret
                  readOnly: true
              env:
                - name: GCAL_ID
                  valueFrom:
                    configMapKeyRef:
                      name: satania-config
                      key: google_calendar_id
                - name: PING_ROLE
                  valueFrom:
                    configMapKeyRef:
                      name: satania-config
                      key: calendar_ping_role
                - name: WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: satania-secret
                      key: discord_webhook_url
          volumes:
            - name: satania_secret_vol
              secret:
                secretName: satania-secret
                items:
                  - key: google_credentials
                    path: creds.json
